### ISSUE TITLE
Can't upload CSV

### ISSUE THREAD

**Issue by blackappsolutions** [CoreMedia/csv-reporting#3]
![grafik](https://user-images.githubusercontent.com/3899967/115407941-bffa3180-a1f0-11eb-9bb9-aa393a89e3bb.png)
![grafik](https://user-images.githubusercontent.com/3899967/115408018-d0121100-a1f0-11eb-99f0-7c5dbd1d9261.png)

Got this error when trying to upload a formerly generated csv (of this extension)

Had to make a minimal adjustment to get it run on 2010.3 
https://github.com/blackappsolutions/csv-reporting/tree/cm10-2010.3_compatibility

Do I have to configure some kind of CsrfTokenHeader in the studio? Can't find something adressing that in the documentation...

![grafik](https://user-images.githubusercontent.com/3899967/115408562-4151c400-a1f1-11eb-87c6-b661a205e9ed.png)

**Comment by kmcherni** [comment]
Moin Markus!

This error should only occur when the user which is attempting to perform the import does not have the proper administrative rights. We trap-door this functionality behind an administrative rights group because of the power of this tool - as a lot of content can be updated at once ;)

If not done so already, please make a new user group in the Studio called "importer" and assign this to the desired users. This can be done through the User Manager in the Studio.

![image](https://user-images.githubusercontent.com/22031412/115420437-22d7d280-a1c9-11eb-9756-fd17e06c0d7f.png)

![image](https://user-images.githubusercontent.com/22031412/115420510-2ff4c180-a1c9-11eb-9b9b-1fe2cc6af226.png)

The only thing the group needs is to be named "importer" exactly - as that's what the extensions looks for. 

I hope this helps! Let me know how this goes when you are able to!

Thanks,
Kevin

**Comment by blackappsolutions** [comment]
Thank you very much. Now its working.
